services:
  front:
    image: 'front'
    container_name: 'front'
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5173:5173"
    networks:
      - frontend

networks:
  frontend:
    name: "frontend"
    driver: bridge