name: Build and Push

on:
  push:
    branches: [main]
  pull_request:

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Copy files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "."
          target: "frontend"
          strip_components: 1

      - name: Deploy ssh
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            export HOST="${{ secrets.HOST }}"
            export AUTH_JWT_SECRET=jwtSecret
            export AUTH_FINGERPRINT=fingerprint

            cd frontend
            docker-compose down front
            docker-compose up front -d